apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: lumina-primary
type: Opaque
stringData:
  access-key-id: YOUR_AWS_ACCESS_KEY_ID
  secret-access-key: YOUR_AWS_SECRET_ACCESS_KEY
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: lumina-dr
type: Opaque
stringData:
  access-key-id: YOUR_AWS_ACCESS_KEY_ID
  secret-access-key: YOUR_AWS_SECRET_ACCESS_KEY
